version: '3'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379

  flower:
    image: mher/flower
    command: celery flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.worker worker --loglevel=info
    volumes:
      - ./app:/code/app
    depends_on:
      - redis